-- =====================================================================
-- KHI Backend — full PostgreSQL schema
--
-- 84 tables · 617 columns · 84 indexes · 1 sequence · 63 foreign keys
--
-- GENERATED FILE. This is not the source of truth and is not executed by
-- the application. The JPA entity classes under
-- src/main/java/ak/dev/khi_backend/ are the source of truth; this file is
-- the DDL Hibernate derives from them under the PostgreSQL dialect, with
-- Spring Boot's naming strategies (PhysicalNamingStrategySnakeCaseImpl
-- and SpringImplicitNamingStrategy).
--
-- At runtime the application does NOT run this script. application.yaml
-- sets spring.jpa.hibernate.ddl-auto: update, so Hibernate reconciles the
-- live database at startup. `update` only ever ADDS — it creates missing
-- tables, columns and indexes, but never drops a column, never changes an
-- existing column's type or nullability, and never adds a missing
-- ON DELETE clause or check constraint to a constraint that already
-- exists. A long-lived database can therefore differ from this file.
-- Use this to provision a FRESH database, or to diff against an existing
-- one; see MIGRATIONS.md next to this file.
--
-- To regenerate:  ./scripts/render-schema.sh
-- =====================================================================

-- ---------------------------------------------------------------------
-- Sequences
-- ---------------------------------------------------------------------

create sequence sessions_seq start with 1 increment by 50;


-- ---------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------

create table about_pages (
    id                   bigint generated by default as identity,
    active               boolean not null,
    body_ckb             TEXT,
    meta_description_ckb varchar(2500),
    subtitle_ckb         varchar(500),
    title_ckb            varchar(300),
    created_at           timestamp(6),
    display_order        integer,
    feature_image_url    TEXT,
    featured             boolean default false not null,
    featured_order       integer,
    founder_bio_ckb      TEXT,
    founder_bio_kmr      TEXT,
    founder_image_url    TEXT,
    founder_name_ckb     varchar(300),
    founder_name_kmr     varchar(300),
    hero_poster_url      TEXT,
    hero_video_url       TEXT,
    body_kmr             TEXT,
    meta_description_kmr varchar(2500),
    subtitle_kmr         varchar(500),
    title_kmr            varchar(300),
    slug_ckb             varchar(200) not null unique,
    slug_kmr             varchar(200) unique,
    stats                jsonb,
    updated_at           timestamp(6),
    primary key (id)
);

create table archive_donations (
    id             bigint generated by default as identity,
    attachment_url TEXT,
    created_at     timestamp(6),
    description    TEXT not null,
    donor_name     varchar(200) not null,
    email          varchar(254) not null,
    estimated_date varchar(80),
    material_type  varchar(120) not null,
    phone          varchar(60),
    status         varchar(30) not null,
    title          varchar(500) not null,
    primary key (id)
);

create table contact_messages (
    id         bigint generated by default as identity,
    created_at timestamp(6),
    email      varchar(254) not null,
    locale     varchar(10),
    message    TEXT not null,
    name       varchar(200) not null,
    phone      varchar(60),
    status     varchar(30) not null,
    subject    varchar(300) not null,
    primary key (id)
);

create table contact_pages (
    id                bigint generated by default as identity,
    active            boolean not null,
    badge_ckb         varchar(200),
    badge_kmr         varchar(200),
    address_ckb       varchar(500),
    description_ckb   TEXT,
    subtitle_ckb      varchar(500),
    title_ckb         varchar(300),
    working_hours_ckb varchar(300),
    created_at        timestamp(6),
    display_order     integer,
    email             varchar(200),
    hero_image_url    TEXT,
    address_kmr       varchar(500),
    description_kmr   TEXT,
    subtitle_kmr      varchar(500),
    title_kmr         varchar(300),
    working_hours_kmr varchar(300),
    latitude          float(53),
    longitude         float(53),
    map_embed_url     TEXT,
    office_type       varchar(40),
    phone             varchar(60),
    secondary_phone   varchar(60),
    slug_ckb          varchar(200) not null unique,
    slug_kmr          varchar(200) unique,
    updated_at        timestamp(6),
    primary key (id)
);

create table donation_settings (
    id                       bigint generated by default as identity,
    account_name             varchar(300),
    account_number           varchar(120),
    archive_enabled          boolean,
    bank_name                varchar(300),
    description_ckb          TEXT,
    description_kmr          TEXT,
    feature_image_url        TEXT,
    featured                 boolean default false not null,
    featured_order           integer,
    financial_enabled        boolean,
    hero_image_url           TEXT,
    iban                     varchar(120),
    payment_instructions_ckb TEXT,
    payment_instructions_kmr TEXT,
    swift_code               varchar(60),
    title_ckb                varchar(500),
    title_kmr                varchar(500),
    primary key (id)
);

create table donation_type_cards (
    id              bigint generated by default as identity,
    active          boolean not null,
    description_ckb varchar(1000),
    description_kmr varchar(1000),
    display_order   integer,
    image_url       varchar(2000) not null,
    title_ckb       varchar(200),
    title_kmr       varchar(200),
    primary key (id)
);

create table featured_items (
    id            bigint generated by default as identity,
    active        boolean not null,
    created_at    timestamp(6),
    description   TEXT not null,
    display_order integer,
    image_alt     varchar(500),
    image_url     TEXT not null,
    locale        varchar(10),
    slug          varchar(300) not null,
    title         varchar(500) not null,
    type          varchar(30) not null,
    updated_at    timestamp(6),
    primary key (id)
);

create table film_reklam_videos (
    id         bigint generated by default as identity,
    created_at timestamp(6) not null,
    mime_type  varchar(100),
    size_bytes bigint not null,
    updated_at timestamp(6) not null,
    video_url  varchar(1200) not null,
    primary key (id)
);

create table financial_donations (
    id                    bigint generated by default as identity,
    amount                numeric(19,2) not null,
    created_at            timestamp(6),
    currency              varchar(10) not null,
    donor_name            varchar(200) not null,
    email                 varchar(254) not null,
    message               TEXT,
    payment_method        varchar(80) not null,
    phone                 varchar(60),
    status                varchar(30) not null,
    transaction_reference varchar(200),
    primary key (id)
);

create table image_album_items (
    id                  bigint generated by default as identity,
    caption_ckb         varchar(500),
    caption_kmr         varchar(500),
    description_ckb     TEXT,
    description_kmr     TEXT,
    embed_url           TEXT,
    external_url        TEXT,
    file_size_bytes     bigint,
    height_px           integer,
    image_url           TEXT,
    mime_type           varchar(50),
    sort_order          integer,
    width_px            integer,
    image_collection_id bigint not null,
    primary key (id)
);

create table image_collection_languages (
    image_collection_id bigint not null,
    language            varchar(10) not null check ((language in ('CKB','KMR'))),
    primary key (image_collection_id, language)
);

create table image_collection_logs (
    id                  bigint generated by default as identity,
    action              varchar(30) not null,
    collection_title    varchar(300),
    details             TEXT,
    image_collection_id bigint,
    performed_by        varchar(150),
    timestamp           timestamp(6) not null,
    primary key (id)
);

create table image_collections (
    id                bigint generated by default as identity,
    collected_by_ckb  varchar(250),
    description_ckb   TEXT,
    location_ckb      varchar(250),
    title_ckb         varchar(300),
    ckb_cover_url     TEXT,
    collection_type   varchar(20) not null check ((collection_type in ('SINGLE','GALLERY','PHOTO_STORY'))),
    created_at        timestamp(6) not null,
    feature_image_url TEXT,
    featured          boolean not null,
    featured_order    integer,
    hover_cover_url   TEXT,
    collected_by_kmr  varchar(250),
    description_kmr   TEXT,
    location_kmr      varchar(250),
    title_kmr         varchar(300),
    kmr_cover_url     TEXT,
    publishment_date  date,
    slug_ckb          varchar(240) unique,
    slug_kmr          varchar(240) unique,
    updated_at        timestamp(6) not null,
    topic_id          bigint,
    primary key (id)
);

create table image_keywords_ckb (
    image_collection_id bigint not null,
    keyword_ckb         varchar(150) not null,
    primary key (image_collection_id, keyword_ckb)
);

create table image_keywords_kmr (
    image_collection_id bigint not null,
    keyword_kmr         varchar(150) not null,
    primary key (image_collection_id, keyword_kmr)
);

create table image_tags_ckb (
    image_collection_id bigint not null,
    tag_ckb             varchar(100) not null,
    primary key (image_collection_id, tag_ckb)
);

create table image_tags_kmr (
    image_collection_id bigint not null,
    tag_kmr             varchar(100) not null,
    primary key (image_collection_id, tag_kmr)
);

create table nav_menu_items (
    id              bigint generated by default as identity,
    active          boolean not null,
    description_ckb TEXT,
    description_kmr TEXT,
    display_order   integer,
    href            varchar(300) not null,
    image_url       TEXT,
    item_key        varchar(60) not null,
    label_ckb       varchar(200) not null,
    label_kmr       varchar(200),
    primary key (id),
    constraint uk_nav_item_key unique (item_key)
);

create table nav_menu_links (
    id            bigint generated by default as identity,
    active        boolean not null,
    display_order integer,
    href          varchar(300) not null,
    label_ckb     varchar(200) not null,
    label_kmr     varchar(200),
    item_id       bigint not null,
    primary key (id)
);

create table news (
    id                  bigint generated by default as identity,
    description_ckb     TEXT,
    title_ckb           varchar(250),
    cover_media_type    varchar(16) check ((cover_media_type in ('IMAGE','VIDEO','AUDIO'))),
    cover_thumbnail_url varchar(1024),
    cover_url           varchar(1024),
    created_at          timestamp(6) not null,
    date_published      date,
    feature_image_url   TEXT,
    featured            boolean not null,
    featured_order      integer,
    description_kmr     TEXT,
    title_kmr           varchar(250),
    media_gallery       jsonb,
    updated_at          timestamp(6) not null,
    category_id         bigint not null,
    sub_category_id     bigint not null,
    primary key (id)
);

create table news_audit_logs (
    id           bigint generated by default as identity,
    action       varchar(20) not null,
    action_time  timestamp(6),
    created_at   timestamp(6) not null,
    news_id      bigint not null,
    note         TEXT,
    performed_by varchar(150),
    updated_at   timestamp(6) not null,
    primary key (id)
);

create table news_categories (
    id       bigint generated by default as identity,
    name_ckb varchar(120) not null unique,
    name_kmr varchar(120) not null,
    primary key (id)
);

create table news_content_languages (
    news_id  bigint not null,
    language varchar(10) not null check ((language in ('CKB','KMR'))),
    primary key (news_id, language)
);

create table news_keywords_ckb (
    news_id     bigint not null,
    keyword_ckb varchar(120) not null,
    primary key (news_id, keyword_ckb)
);

create table news_keywords_kmr (
    news_id     bigint not null,
    keyword_kmr varchar(120) not null,
    primary key (news_id, keyword_kmr)
);

create table news_sub_categories (
    id          bigint generated by default as identity,
    name_ckb    varchar(120) not null,
    name_kmr    varchar(120) not null,
    category_id bigint not null,
    primary key (id),
    unique (category_id, name_ckb)
);

create table news_tags_ckb (
    news_id bigint not null,
    tag_ckb varchar(80) not null,
    primary key (news_id, tag_ckb)
);

create table news_tags_kmr (
    news_id bigint not null,
    tag_kmr varchar(80) not null,
    primary key (news_id, tag_kmr)
);

create table partners (
    id              bigint generated by default as identity,
    active          boolean not null,
    description_ckb TEXT,
    description_kmr TEXT,
    display_order   integer,
    logo_url        TEXT,
    name_ckb        varchar(300) not null,
    name_kmr        varchar(300),
    website_url     TEXT,
    primary key (id)
);

create table project_content_languages (
    project_id bigint not null,
    language   varchar(10) not null check ((language in ('CKB','KMR'))),
    primary key (project_id, language)
);

create table project_keyword_map_ckb (
    project_id bigint not null,
    keyword_id bigint not null,
    primary key (project_id, keyword_id)
);

create table project_keyword_map_kmr (
    project_id bigint not null,
    keyword_id bigint not null,
    primary key (project_id, keyword_id)
);

create table project_keywords (
    id   bigint generated by default as identity,
    name varchar(191) not null,
    primary key (id),
    constraint uq_project_keywords_name unique (name)
);

create table project_log (
    id         bigint generated by default as identity,
    action     varchar(50) not null,
    created_at timestamp(6) not null,
    field_name varchar(50),
    new_value  text,
    old_value  text,
    project_id bigint not null,
    primary key (id)
);

create table project_tag_map_ckb (
    project_id bigint not null,
    tag_id     bigint not null,
    primary key (project_id, tag_id)
);

create table project_tag_map_kmr (
    project_id bigint not null,
    tag_id     bigint not null,
    primary key (project_id, tag_id)
);

create table project_tags (
    id   bigint generated by default as identity,
    name varchar(128) not null,
    primary key (id),
    constraint uq_project_tags_name unique (name)
);

create table projects (
    id                  bigint generated by default as identity,
    created_at          timestamp(6) not null,
    created_by          varchar(120),
    updated_at          timestamp(6) not null,
    updated_by          varchar(120),
    description_ckb     TEXT,
    location_ckb        varchar(255),
    title_ckb           varchar(255),
    cover_media_type    varchar(16) check ((cover_media_type in ('IMAGE','VIDEO','AUDIO'))),
    cover_thumbnail_url varchar(1024),
    cover_url           varchar(1024),
    feature_image_url   TEXT,
    featured            boolean not null,
    featured_order      integer,
    description_kmr     TEXT,
    location_kmr        varchar(255),
    title_kmr           varchar(255),
    media_gallery       jsonb,
    project_date        date,
    project_type_ckb    varchar(128),
    project_type_kmr    varchar(128),
    status              varchar(32) not null check ((status in ('ACTIVE','ONGOING','COMPLETED','ARCHIVED'))),
    primary key (id)
);

create table publishment_topics (
    id          bigint generated by default as identity,
    created_at  timestamp(6) not null,
    entity_type varchar(20) not null,
    name_ckb    varchar(300),
    name_kmr    varchar(300),
    updated_at  timestamp(6) not null,
    primary key (id)
);

create table service_audit_logs (
    id           bigint generated by default as identity,
    action       varchar(30) not null,
    details      TEXT,
    performed_by varchar(150),
    request_id   varchar(120),
    service_id   bigint not null,
    service_type varchar(100),
    timestamp    timestamp(6) not null,
    primary key (id)
);

create table service_contents (
    id                  bigint generated by default as identity,
    description         TEXT,
    feature_description varchar(1000),
    language_code       varchar(10) not null,
    title               varchar(300) not null,
    service_id          bigint not null,
    primary key (id),
    constraint uq_service_content_lang unique (service_id, language_code)
);

create table service_feature_images (
    service_id    bigint not null,
    image_url     TEXT,
    display_order integer not null,
    primary key (service_id, display_order)
);

create table service_gallery_media (
    service_id    bigint not null,
    alt           varchar(500),
    poster_url    TEXT,
    media_type    varchar(10),
    url           TEXT,
    display_order integer not null,
    primary key (service_id, display_order)
);

create table service_partners (
    service_id    bigint not null,
    partner_id    bigint,
    display_order integer not null,
    primary key (service_id, display_order)
);

create table service_thumbnail_images (
    service_id    bigint not null,
    image_url     TEXT,
    display_order integer not null,
    primary key (service_id, display_order)
);

create table services (
    id                bigint generated by default as identity,
    active            boolean,
    created_at        timestamp(6),
    feature_image_url TEXT,
    featured          boolean default false not null,
    featured_order    integer,
    hero_poster_url   TEXT,
    hero_video_url    TEXT,
    layout_type       varchar(80),
    location          varchar(200),
    nav_anchor_id     varchar(160),
    published_at      timestamp(6),
    service_type      varchar(100) not null,
    sort_order        integer,
    updated_at        timestamp(6),
    primary key (id)
);

create table sessions (
    id               bigint not null,
    device_info      varchar(255),
    expires_at       timestamp(6) with time zone not null,
    ip_address       varchar(255),
    is_active        boolean not null,
    login_timestamp  timestamp(6) with time zone not null,
    logout_timestamp timestamp(6) with time zone,
    session_id       varchar(255) not null unique,
    user_id          bigint not null,
    primary key (id)
);

create table site_settings (
    id                  bigint generated by default as identity,
    donate_image_url    varchar(1200),
    logo_url            varchar(1200),
    max_featured_slides integer not null,
    updated_at          timestamp(6),
    primary key (id)
);

create table social_links (
    id            bigint generated by default as identity,
    active        boolean not null,
    display_order integer,
    label_ckb     varchar(200),
    label_kmr     varchar(200),
    platform      varchar(60) not null,
    url           TEXT not null,
    primary key (id),
    constraint uk_social_platform unique (platform)
);

create table sound_reklam_videos (
    id         bigint generated by default as identity,
    created_at timestamp(6) not null,
    mime_type  varchar(100),
    size_bytes bigint not null,
    updated_at timestamp(6) not null,
    video_url  varchar(1200) not null,
    primary key (id)
);

create table sound_track_attachments (
    id               bigint generated by default as identity,
    attachment_order integer,
    attachment_type  varchar(20) not null check ((attachment_type in ('PDF','VIDEO','IMAGE','AUDIO','OTHER'))),
    file_url         varchar(1200) not null,
    mime_type        varchar(100),
    size_bytes       bigint not null,
    title            varchar(300),
    sound_track_id   bigint not null,
    primary key (id)
);

create table sound_track_brochures (
    id                  bigint generated by default as identity,
    brochure_order      integer,
    caption             varchar(300),
    image_url           varchar(1200) not null,
    sound_track_file_id bigint not null,
    primary key (id)
);

create table sound_track_content_languages (
    sound_track_id bigint not null,
    language       varchar(10) not null check ((language in ('CKB','KMR'))),
    primary key (sound_track_id, language)
);

create table sound_track_directors (
    sound_track_id bigint not null,
    director_name  varchar(255) not null,
    primary key (sound_track_id, director_name)
);

create table sound_track_files (
    id               bigint generated by default as identity,
    audio_channel    varchar(10) check ((audio_channel in ('MONO','STEREO'))),
    bit_rate         varchar(50),
    duration_seconds bigint not null,
    embed_url        TEXT,
    external_url     TEXT,
    file_format      varchar(50),
    file_type        varchar(10) not null check ((file_type in ('AUDIO','VIDEO','MP3','WAV','OGG','AAC','FLAC','OTHER'))),
    file_url         varchar(1200),
    form             varchar(150),
    genre            varchar(100),
    publishment_year integer,
    recording_venue  varchar(500),
    sample_rate      varchar(50),
    size_bytes       bigint not null,
    title            varchar(300),
    sound_track_id   bigint not null,
    primary key (id)
);

create table sound_track_keywords_ckb (
    sound_track_id bigint not null,
    keyword_ckb    varchar(100) not null,
    primary key (sound_track_id, keyword_ckb)
);

create table sound_track_keywords_kmr (
    sound_track_id bigint not null,
    keyword_kmr    varchar(100) not null,
    primary key (sound_track_id, keyword_kmr)
);

create table sound_track_locations (
    sound_track_id bigint not null,
    location       varchar(255) not null,
    primary key (sound_track_id, location)
);

create table sound_track_logs (
    id                 bigint generated by default as identity,
    action             varchar(40) not null,
    actor_id           varchar(120),
    actor_name         varchar(200),
    created_at         timestamp(6) not null,
    details            varchar(8000),
    meta               varchar(1000),
    request_id         varchar(120),
    sound_track_ref_id bigint,
    sound_track_title  varchar(300),
    sound_track_id     bigint,
    primary key (id)
);

create table sound_track_tags_ckb (
    sound_track_id bigint not null,
    tag_ckb        varchar(60) not null,
    primary key (sound_track_id, tag_ckb)
);

create table sound_track_tags_kmr (
    sound_track_id bigint not null,
    tag_kmr        varchar(60) not null,
    primary key (sound_track_id, tag_kmr)
);

create table sound_tracks (
    id                   bigint generated by default as identity,
    album_name           varchar(300),
    is_album_of_memories boolean not null,
    cd_number            integer,
    description_ckb      TEXT,
    title_ckb            varchar(200),
    ckb_cover_url        varchar(1000),
    created_at           timestamp(6) not null,
    feature_image_url    TEXT,
    featured             boolean not null,
    featured_order       integer,
    hover_cover_url      varchar(1000),
    description_kmr      TEXT,
    title_kmr            varchar(200),
    kmr_cover_url        varchar(1000),
    publishment_year     integer,
    reader_name          varchar(255),
    sound_type           varchar(100) not null,
    terms                varchar(200),
    is_institute_project boolean not null,
    total_tracks         integer,
    track_state          varchar(10) not null check ((track_state in ('SINGLE','MULTI'))),
    updated_at           timestamp(6) not null,
    topic_id             bigint,
    primary key (id)
);

create table team_members (
    id            bigint generated by default as identity,
    active        boolean not null,
    bio_ckb       TEXT,
    bio_kmr       TEXT,
    display_order integer,
    image_url     TEXT,
    name_ckb      varchar(300) not null,
    name_kmr      varchar(300),
    office        varchar(200),
    role_ckb      varchar(300) not null,
    role_kmr      varchar(300),
    primary key (id)
);

create table token_blacklist (
    id             bigint generated by default as identity,
    blacklisted_at timestamp(6) with time zone not null,
    expires_at     timestamp(6) with time zone not null,
    token          varchar(512) not null unique,
    primary key (id)
);

create table users_tbl (
    user_id                bigint generated by default as identity,
    created_at             timestamp(6) with time zone,
    email                  varchar(160) not null unique,
    failed_attempts        integer not null,
    is_activated           boolean not null,
    is_locked              boolean not null,
    lock_time              timestamp(6) with time zone,
    name                   varchar(120) not null,
    password               varchar(255) not null,
    password_expiry_date   timestamp(6) with time zone,
    pincode                bigint,
    profile_image          varchar(500),
    reset_token            varchar(120),
    reset_token_expiration timestamp(6) with time zone,
    role                   varchar(30) not null check ((role in ('GUEST','EMPLOYEE','ADMIN','SUPER_ADMIN'))),
    updated_at             timestamp(6) with time zone,
    username               varchar(80) not null unique,
    primary key (user_id)
);

create table video_cast_members (
    video_id      bigint not null,
    image_url     TEXT,
    name_ckb      varchar(300),
    name_kmr      varchar(300),
    role_ckb      varchar(300),
    role_kmr      varchar(300),
    display_order integer not null,
    primary key (video_id, display_order)
);

create table video_clip_items (
    id               bigint generated by default as identity,
    clip_number      integer,
    description_ckb  TEXT,
    description_kmr  TEXT,
    duration_seconds integer,
    embed_url        TEXT,
    external_url     TEXT,
    file_format      varchar(20),
    file_size_mb     float(53),
    resolution       varchar(20),
    title_ckb        varchar(300),
    title_kmr        varchar(300),
    url              TEXT,
    video_id         bigint not null,
    primary key (id)
);

create table video_content_languages (
    video_id bigint not null,
    language varchar(10) not null check ((language in ('CKB','KMR'))),
    primary key (video_id, language)
);

create table video_highlight_clips (
    video_id         bigint not null,
    duration_seconds integer,
    embed_url        TEXT,
    title_ckb        varchar(300),
    title_kmr        varchar(300),
    clip_url         TEXT,
    display_order    integer not null,
    primary key (video_id, display_order)
);

create table video_keywords_ckb (
    video_id    bigint not null,
    keyword_ckb varchar(150) not null,
    primary key (video_id, keyword_ckb)
);

create table video_keywords_kmr (
    video_id    bigint not null,
    keyword_kmr varchar(150) not null,
    primary key (video_id, keyword_kmr)
);

create table video_logs (
    id           bigint generated by default as identity,
    action       varchar(30) not null,
    details      TEXT,
    performed_by varchar(150),
    timestamp    timestamp(6) not null,
    video_id     bigint,
    video_title  varchar(300),
    primary key (id)
);

create table video_source_files (
    video_id         bigint not null,
    duration_seconds integer,
    embed_url        TEXT,
    external_url     TEXT,
    label            varchar(300),
    is_main          boolean not null,
    url              TEXT,
    display_order    integer not null,
    primary key (video_id, display_order)
);

create table video_tags_ckb (
    video_id bigint not null,
    tag_ckb  varchar(100) not null,
    primary key (video_id, tag_ckb)
);

create table video_tags_kmr (
    video_id bigint not null,
    tag_kmr  varchar(100) not null,
    primary key (video_id, tag_kmr)
);

create table videos (
    id                   bigint generated by default as identity,
    is_album_of_memories boolean not null,
    description_ckb      TEXT,
    director_ckb         varchar(250),
    location_ckb         varchar(250),
    producer_ckb         varchar(250),
    title_ckb            varchar(300),
    ckb_cover_url        varchar(1000),
    created_at           timestamp(6) not null,
    duration_seconds     integer,
    feature_image_url    TEXT,
    featured             boolean not null,
    featured_order       integer,
    file_format          varchar(20),
    file_size_mb         float(53),
    hover_cover_url      varchar(1000),
    description_kmr      TEXT,
    director_kmr         varchar(250),
    location_kmr         varchar(250),
    producer_kmr         varchar(250),
    title_kmr            varchar(300),
    kmr_cover_url        varchar(1000),
    publishment_date     date,
    resolution           varchar(20),
    source_embed_url     TEXT,
    source_external_url  TEXT,
    source_url           TEXT,
    updated_at           timestamp(6) not null,
    video_type           varchar(20) not null check ((video_type in ('FILM','VIDEO_CLIP'))),
    topic_id             bigint,
    primary key (id)
);

create table writing_book_genres (
    writing_id bigint not null,
    book_genre varchar(30) not null check ((book_genre in ('POETRY','NOVEL','SHORT_STORY','DRAMA','HISTORY','BIOGRAPHY','PHILOSOPHY','RELIGION','FOLKLORE','POLITICS','SOCIOLOGY','ECONOMICS','LAW','LINGUISTICS','ARTS','CULTURAL','SCIENCE','MEDICINE','EDUCATIONAL','CHILDREN','TRAVEL','OTHER','ESSAY','POLITICAL','ACADEMIC'))),
    primary key (writing_id, book_genre)
);

create table writing_content_languages (
    writing_id bigint not null,
    language   varchar(10) not null check ((language in ('CKB','KMR'))),
    primary key (writing_id, language)
);

create table writing_keywords_ckb (
    writing_id  bigint not null,
    keyword_ckb varchar(120) not null,
    primary key (writing_id, keyword_ckb)
);

create table writing_keywords_kmr (
    writing_id  bigint not null,
    keyword_kmr varchar(120) not null,
    primary key (writing_id, keyword_kmr)
);

create table writing_logs (
    id             bigint generated by default as identity,
    action         varchar(40) not null,
    actor_id       varchar(120),
    actor_name     varchar(200),
    created_at     timestamp(6) not null,
    details        TEXT,
    meta           varchar(1000),
    request_id     varchar(120),
    writing_id_ref bigint not null,
    writing_id     bigint,
    primary key (id)
);

create table writing_tags_ckb (
    writing_id bigint not null,
    tag_ckb    varchar(80) not null,
    primary key (writing_id, tag_ckb)
);

create table writing_tags_kmr (
    writing_id bigint not null,
    tag_kmr    varchar(80) not null,
    primary key (writing_id, tag_kmr)
);

create table writings (
    id                     bigint generated by default as identity,
    description_ckb        TEXT,
    file_format_ckb        varchar(20) check ((file_format_ckb in ('PDF','DOCX','DOC','TXT','EPUB','ODT','RTF','HTML','OTHER'))),
    file_size_bytes_ckb    bigint,
    file_url_ckb           varchar(1000),
    genre_ckb              varchar(150),
    page_count_ckb         integer,
    title_ckb              varchar(300),
    writer_ckb             varchar(200),
    ckb_cover_url          TEXT,
    created_at             timestamp(6) not null,
    feature_image_url      TEXT,
    featured               boolean not null,
    featured_order         integer,
    hover_cover_url        TEXT,
    description_kmr        TEXT,
    file_format_kmr        varchar(20) check ((file_format_kmr in ('PDF','DOCX','DOC','TXT','EPUB','ODT','RTF','HTML','OTHER'))),
    file_size_bytes_kmr    bigint,
    file_url_kmr           varchar(1000),
    genre_kmr              varchar(150),
    page_count_kmr         integer,
    title_kmr              varchar(300),
    writer_kmr             varchar(200),
    kmr_cover_url          TEXT,
    published_by_institute boolean not null,
    series_id              varchar(100),
    series_name            varchar(300),
    series_order           float(53),
    series_total_books     integer,
    updated_at             timestamp(6) not null,
    parent_book_id         bigint,
    topic_id               bigint,
    primary key (id)
);


-- ---------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------

create index idx_about_slug_ckb on about_pages (slug_ckb);
create index idx_about_slug_kmr on about_pages (slug_kmr);
create index idx_about_active on about_pages (active);
create index idx_archive_donation_status_created on archive_donations (status, created_at);
create index idx_contact_message_status_created on contact_messages (status, created_at);
create index idx_contact_slug_ckb on contact_pages (slug_ckb);
create index idx_contact_slug_kmr on contact_pages (slug_kmr);
create index idx_contact_active on contact_pages (active);
create index idx_featured_locale_active_order on featured_items (locale, active, display_order);
create index idx_financial_donation_status_created on financial_donations (status, created_at);
create index idx_album_item_collection_id on image_album_items (image_collection_id);
create index idx_img_log_collection_id on image_collection_logs (image_collection_id);
create index idx_img_log_action on image_collection_logs (action);
create index idx_img_log_timestamp on image_collection_logs (timestamp);
create index idx_img_collection_type on image_collections (collection_type);
create index idx_img_topic on image_collections (topic_id);
create index idx_img_title_ckb on image_collections (title_ckb);
create index idx_img_title_kmr on image_collections (title_kmr);
create index idx_img_publishment_date on image_collections (publishment_date);
create index idx_img_created_at on image_collections (created_at);
create index idx_img_updated_at on image_collections (updated_at);
create index idx_news_date_published on news (date_published desc);
create index idx_news_created_at on news (created_at desc);
create index idx_news_category_name_ckb on news_categories (name_ckb);
create index idx_news_sub_category_name_ckb on news_sub_categories (name_ckb);
create index idx_partner_active_order on partners (active, display_order);
create index idx_project_log_project_id on project_log (project_id);
create index idx_project_log_action on project_log (action);
create index idx_project_log_created_at on project_log (created_at);
create index idx_projects_type_ckb on projects (project_type_ckb);
create index idx_projects_type_kmr on projects (project_type_kmr);
create index idx_projects_status on projects (status);
create index idx_projects_date on projects (project_date);
create index idx_topic_entity_type on publishment_topics (entity_type);
create index idx_topic_name_ckb on publishment_topics (entity_type, name_ckb);
create index idx_topic_name_kmr on publishment_topics (entity_type, name_kmr);
create index idx_sal_service_id on service_audit_logs (service_id);
create index idx_sal_action on service_audit_logs (action);
create index idx_sal_timestamp on service_audit_logs (timestamp);
create index idx_service_content_service_id on service_contents (service_id);
create index idx_service_content_lang on service_contents (language_code);
create index idx_service_type on services (service_type);
create index idx_service_active on services (active);
create index idx_service_published_at on services (published_at);
create index idx_service_sort_order on services (sort_order);
create index idx_attachment_track on sound_track_attachments (sound_track_id);
create index idx_attachment_type on sound_track_attachments (attachment_type);
create index idx_brochure_file on sound_track_brochures (sound_track_file_id);
create index idx_sound_file_type on sound_track_files (file_type);
create index idx_sound_file_track on sound_track_files (sound_track_id);
create index idx_stlog_soundtrack on sound_track_logs (sound_track_id);
create index idx_stlog_action on sound_track_logs (action);
create index idx_stlog_created_at on sound_track_logs (created_at);
create index idx_soundtrack_type on sound_tracks (sound_type);
create index idx_soundtrack_state on sound_tracks (track_state);
create index idx_soundtrack_album on sound_tracks (is_album_of_memories);
create index idx_soundtrack_topic on sound_tracks (topic_id);
create index idx_soundtrack_created_at on sound_tracks (created_at);
create index idx_soundtrack_updated_at on sound_tracks (updated_at);
create index idx_team_active_order on team_members (active, display_order);
create index idx_clip_video_id on video_clip_items (video_id);
create index idx_clip_clip_number on video_clip_items (clip_number);
create index idx_vlog_video_id on video_logs (video_id);
create index idx_vlog_action on video_logs (action);
create index idx_vlog_timestamp on video_logs (timestamp);
create index idx_video_type on videos (video_type);
create index idx_video_album on videos (is_album_of_memories);
create index idx_video_pub_date on videos (publishment_date);
create index idx_video_topic on videos (topic_id);
create index idx_video_title_ckb on videos (title_ckb);
create index idx_video_title_kmr on videos (title_kmr);
create index idx_wlog_writing on writing_logs (writing_id);
create index idx_wlog_writing_ref on writing_logs (writing_id_ref);
create index idx_wlog_action on writing_logs (action);
create index idx_wlog_created_at on writing_logs (created_at);
create index idx_writing_topic_id on writings (topic_id);
create index idx_writing_institute on writings (published_by_institute);
create index idx_writing_created_at on writings (created_at);
create index idx_writing_updated_at on writings (updated_at);
create index idx_writer_ckb on writings (writer_ckb);
create index idx_writer_kmr on writings (writer_kmr);
create index idx_series_id on writings (series_id);
create index idx_series_composite on writings (series_id, series_order);
create index idx_parent_book on writings (parent_book_id);


-- ---------------------------------------------------------------------
-- Foreign keys and table constraints
-- ---------------------------------------------------------------------

alter table if exists image_album_items add constraint FK4ggc6orehjh9f48oahen5rnb0 foreign key (image_collection_id) references image_collections;
alter table if exists image_collection_languages add constraint FKacppj7uinqyn113j6refcwjag foreign key (image_collection_id) references image_collections;
alter table if exists image_collections add constraint FKhrd9p3e61hqs26p4oyqfkloau foreign key (topic_id) references publishment_topics;
alter table if exists image_keywords_ckb add constraint FKm8l7ifco7xqlqidxps0u36hnj foreign key (image_collection_id) references image_collections;
alter table if exists image_keywords_kmr add constraint FKtib08nvhevrei6y67wdpy3y4k foreign key (image_collection_id) references image_collections;
alter table if exists image_tags_ckb add constraint FKmdnkpu29vys10ypw9cvkdaec5 foreign key (image_collection_id) references image_collections;
alter table if exists image_tags_kmr add constraint FKsl4dri7ji57mqf4a9fqt2vlq9 foreign key (image_collection_id) references image_collections;
alter table if exists nav_menu_links add constraint FKa6d983cxkve0bjfrt8n65jxrv foreign key (item_id) references nav_menu_items;
alter table if exists news add constraint FKc4wejd2hk38ntj64b4w9bk1bh foreign key (category_id) references news_categories;
alter table if exists news add constraint FKnnta97ju8f8ewmxaqsyvbuehe foreign key (sub_category_id) references news_sub_categories;
alter table if exists news_content_languages add constraint FK4xv6k4yo1dt0w0lhgoviv5iwc foreign key (news_id) references news;
alter table if exists news_keywords_ckb add constraint FKcqo90hqybb8xnr65xixf6lgdg foreign key (news_id) references news;
alter table if exists news_keywords_kmr add constraint FKkp11okgswecyrsd7yc7raqamt foreign key (news_id) references news;
alter table if exists news_sub_categories add constraint FK5iqced7gsrk8icqsvxmgb2085 foreign key (category_id) references news_categories;
alter table if exists news_tags_ckb add constraint FK7ttfygca65xb1ylf8e478lx77 foreign key (news_id) references news;
alter table if exists news_tags_kmr add constraint FKo8sxon0dylvks5ak1qr1dv7j1 foreign key (news_id) references news;
alter table if exists project_content_languages add constraint FKp6epno5f1wplvqi733btpqhq foreign key (project_id) references projects;
alter table if exists project_keyword_map_ckb add constraint FKa6toxrhhfgdvp068frr37lwck foreign key (keyword_id) references project_keywords;
alter table if exists project_keyword_map_ckb add constraint FKnmpbapk0osf1g9ogtexvvns4p foreign key (project_id) references projects;
alter table if exists project_keyword_map_kmr add constraint FKk7fbcylehr3y0d3k5or9lah4o foreign key (keyword_id) references project_keywords;
alter table if exists project_keyword_map_kmr add constraint FKk0ho65tnvgctud6b8yww8p5x0 foreign key (project_id) references projects;
alter table if exists project_log add constraint fk_project_log_project foreign key (project_id) references projects on delete cascade;
alter table if exists project_tag_map_ckb add constraint FK6tfn8yh66slp4ewphxj0vv9pl foreign key (tag_id) references project_tags;
alter table if exists project_tag_map_ckb add constraint FKb5gya6ctcexvds1srcg7eyhkn foreign key (project_id) references projects;
alter table if exists project_tag_map_kmr add constraint FKt57ac4y9ko80phk6e7nupq9ci foreign key (tag_id) references project_tags;
alter table if exists project_tag_map_kmr add constraint FK5wchqmkd31cys8vkjiqnot3k0 foreign key (project_id) references projects;
alter table if exists service_contents add constraint FKbdip9fv9v0ycvbhlirff2guvw foreign key (service_id) references services;
alter table if exists service_feature_images add constraint FK8a1sk090lfepqes2m16kxpuc6 foreign key (service_id) references services;
alter table if exists service_gallery_media add constraint FK5kgfgljox9yfy8fwudfhgg07s foreign key (service_id) references services;
alter table if exists service_partners add constraint FK8xw79143k48hjpqo6kttlop32 foreign key (service_id) references services;
alter table if exists service_thumbnail_images add constraint FKongumjw661jtu6uw9h569xmu7 foreign key (service_id) references services;
alter table if exists sessions add constraint FK4roog0oq6cb0essbkvmo0b8vl foreign key (user_id) references users_tbl;
alter table if exists sound_track_attachments add constraint FK14x7p52gv8o66jypq3m2ffj4f foreign key (sound_track_id) references sound_tracks;
alter table if exists sound_track_brochures add constraint FKmxed3elyqi3naxoxfrcu25bku foreign key (sound_track_file_id) references sound_track_files;
alter table if exists sound_track_content_languages add constraint FKlmcpar60c7vrhuds9xjo6c0ey foreign key (sound_track_id) references sound_tracks;
alter table if exists sound_track_directors add constraint FK6yi7o7lpuyckhxg5krw7vtbuf foreign key (sound_track_id) references sound_tracks;
alter table if exists sound_track_files add constraint FK9os0yue7wt3m7btowql8ui6d9 foreign key (sound_track_id) references sound_tracks;
alter table if exists sound_track_keywords_ckb add constraint FKh47400jiedqrc23lhy6ge01di foreign key (sound_track_id) references sound_tracks;
alter table if exists sound_track_keywords_kmr add constraint FKl5i625b80um6vqnh3jld5iakp foreign key (sound_track_id) references sound_tracks;
alter table if exists sound_track_locations add constraint FKprwpdd3pl3d49oh2ywyxinsub foreign key (sound_track_id) references sound_tracks;
alter table if exists sound_track_logs add constraint FK902vhlmp348o151liql4bby2p foreign key (sound_track_id) references sound_tracks;
alter table if exists sound_track_tags_ckb add constraint FKdhhahfx0nvhu1126h2wcmvtvs foreign key (sound_track_id) references sound_tracks;
alter table if exists sound_track_tags_kmr add constraint FKil5261k5dr3dcd2lr1k4p76lp foreign key (sound_track_id) references sound_tracks;
alter table if exists sound_tracks add constraint FKlmi6arke075scjoh86f6718my foreign key (topic_id) references publishment_topics;
alter table if exists video_cast_members add constraint FKpxu0r9pkoo55fvv48cwcvqt9j foreign key (video_id) references videos;
alter table if exists video_clip_items add constraint FKgl9o0a6shqwatgcmrpx1fhnsd foreign key (video_id) references videos;
alter table if exists video_content_languages add constraint FK9rd69aga70r3v4yt81agxic5s foreign key (video_id) references videos;
alter table if exists video_highlight_clips add constraint FKsuqsj8hiqwn1ue6vgtyhw22s0 foreign key (video_id) references videos;
alter table if exists video_keywords_ckb add constraint FKfaj1wa67xlyt7ofanxnaaoi54 foreign key (video_id) references videos;
alter table if exists video_keywords_kmr add constraint FKa86b4936ptsam2sdni8x6ijh0 foreign key (video_id) references videos;
alter table if exists video_source_files add constraint FKb1ma0052g6qxscbb34sxcqcow foreign key (video_id) references videos;
alter table if exists video_tags_ckb add constraint FK9nu5td64ji0ougld26ti6hm5q foreign key (video_id) references videos;
alter table if exists video_tags_kmr add constraint FKjy0023m2gmtkq72o7o2483fut foreign key (video_id) references videos;
alter table if exists videos add constraint FKth0fd8i64p3widkq96nd4vwv1 foreign key (topic_id) references publishment_topics;
alter table if exists writing_book_genres add constraint FKptbfo5djq8yql1c7tgjsxtmd1 foreign key (writing_id) references writings;
alter table if exists writing_content_languages add constraint FK8hryyaiw8vt6fdsqwooio2pem foreign key (writing_id) references writings;
alter table if exists writing_keywords_ckb add constraint FKefydnwaqgb0ok1jxpeloyk9j7 foreign key (writing_id) references writings;
alter table if exists writing_keywords_kmr add constraint FK3vuifuhi1yqlceb09tv918myh foreign key (writing_id) references writings;
alter table if exists writing_logs add constraint FKo2xkjdh2dh1ajfju881ohgjmy foreign key (writing_id) references writings;
alter table if exists writing_tags_ckb add constraint FKkeqcnxc23m1b3eujyu78u2igl foreign key (writing_id) references writings;
alter table if exists writing_tags_kmr add constraint FKfjj4t1j9076jmbj4kb8na00p0 foreign key (writing_id) references writings;
alter table if exists writings add constraint FK2dgv656nyh6525dk8imasq807 foreign key (parent_book_id) references writings;
alter table if exists writings add constraint FK27bp8ns3rfef3g1dita2ldeka foreign key (topic_id) references publishment_topics;
